// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ohDUrl0KzyxnoYpIWkFjZvx9xp5SDQ0',
    appId: '1:657955651810:web:101cdfe3721b60b5ae5ebb',
    messagingSenderId: '657955651810',
    projectId: 'greendme-8e44c',
    authDomain: 'greendme-8e44c.firebaseapp.com',
    storageBucket: 'greendme-8e44c.firebasestorage.app',
    measurementId: 'G-Y9ECS1Y1PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCXbwRGwWC-_YATRsO0Mtvy9X9nKQloQ',
    appId: '1:657955651810:android:19c04ae0fe2a6440ae5ebb',
    messagingSenderId: '657955651810',
    projectId: 'greendme-8e44c',
    storageBucket: 'greendme-8e44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEi35RuLSvQrZD6iePPfbKV4YfuQZAAk',
    appId: '1:657955651810:ios:72177ebdc96f1a10ae5ebb',
    messagingSenderId: '657955651810',
    projectId: 'greendme-8e44c',
    storageBucket: 'greendme-8e44c.firebasestorage.app',
    iosBundleId: 'com.example.greedmeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWEi35RuLSvQrZD6iePPfbKV4YfuQZAAk',
    appId: '1:657955651810:ios:72177ebdc96f1a10ae5ebb',
    messagingSenderId: '657955651810',
    projectId: 'greendme-8e44c',
    storageBucket: 'greendme-8e44c.firebasestorage.app',
    iosBundleId: 'com.example.greedmeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ohDUrl0KzyxnoYpIWkFjZvx9xp5SDQ0',
    appId: '1:657955651810:web:449101ac2a69649dae5ebb',
    messagingSenderId: '657955651810',
    projectId: 'greendme-8e44c',
    authDomain: 'greendme-8e44c.firebaseapp.com',
    storageBucket: 'greendme-8e44c.firebasestorage.app',
    measurementId: 'G-9DJL0CHVCS',
  );
}
